exports.NotificationTypes = {
    GOT_NEW_ORDER: 'GOT_NEW_ORDER',
    CANCEL_USER_ORDER: 'CANCEL_USER_ORDER',
    TRADE_UPDATE: 'TRADE_UPDATE',
    ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
    MARKET_TICKER: 'MARKET_TICKER'
};
