exports.MessageTypes = {
  USER_SIGNED_UP: 'USER_SIGNED_UP',
  USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
  USER_KYC_SUBMITTED: 'USER_KYC_SUBMITTED',
  USER_KYC_VERIFIED: 'USER_KYC_VERIFIED',
  USER_KYC_UPDATE: 'USER_KYC_UPDATE',
  USER_DEPOSIT_REQUEST: 'USER_DEPOSIT_REQUEST',
  USER_WITHDRAW_REQUEST: 'USER_WITHDRAW_REQUEST',
  USER_DEPOSITED_AMOUNT: 'USER_DEPOSITED_AMOUNT',
  USER_WITHDRAW_AMOUNT: 'USER_WITHDRAW_AMOUNT',
  NEW_ORDER_PLACED: 'NEW_ORDER_PLACED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_TRADED: 'ORDER_TRADED',
  SERVER_BUG: 'SERVER_BUG',

  COIN_DEPOSIT_INIT: 'COIN_DEPOSIT_INIT',
  COIN_DEPOSIT_FAILED: 'COIN_DEPOSIT_FAILED',
  COIN_DEPOSIT_COMPLETE: 'COIN_DEPOSIT_COMPLETE',
  COIN_DEPOSIT_UPDATE: 'COIN_DEPOSIT_UPDATE',

  COIN_WITHDRAWAL_INIT: 'COIN_WITHDRAWAL_INIT',
  COIN_WITHDRAWAL_FAILED: 'COIN_WITHDRAWAL_FAILED',
  COIN_WITHDRAWAL_COMPLETE: 'COIN_WITHDRAWAL_COMPLETE',
  COIN_WITHDRAWAL_UPDATE: 'COIN_WITHDRAWAL_UPDATE',

  INR_DEPOSIT_INIT: 'INR_DEPOSIT_INIT',
  INR_DEPOSIT_FAILED: 'INR_DEPOSIT_FAILED',
  INR_DEPOSIT_COMPLETE: 'INR_DEPOSIT_COMPLETE',
  INR_DEPOSIT_UPDATE: 'INR_DEPOSIT_UPDATE',

  IEO_SALE_UPDATE: 'IEO_SALE_UPDATE',

  INR_WITHDRAWAL_INIT: 'INR_WITHDRAWAL_INIT',
  INR_WITHDRAWAL_FAILED: 'INR_WITHDRAWAL_FAILED',
  INR_WITHDRAWAL_COMPLETE: 'INR_WITHDRAWAL_COMPLETE',
  INR_DEPOSIT_UPDATE: 'INR_DEPOSIT_UPDATE',
};

