exports.allowedModes = {
  CREDIT_CARD: 'CREDIT_CARD',
  NETBANKING: 'NETBANKING',
  OTHERS: 'OTHERS'
};
exports.allowedTypes = {
  ADD_TO_PLATFORM: 'ADD_TO_PLATFORM',
  WITHDRAW_FROM_PLATFORM: 'WITHDRAW_FROM_PLATFORM',
  OTHERS: 'OTHERS',
  // ADD_QUESTION_COST: 'ADD_QUESTION_COST',
  // QUESTION_TRADE_BONUS: 'QUESTION_TRADE_BONUS',
};
exports.transactionStatus = {
  PENDING: 'PENDING',
  DECLINED: 'DECLINED',
  DEFERRED: 'DEFERRED',
  COMPLETE: 'COMPLETE',
  CANCELLED: 'CANCELLED'
};
